[package]
name = "kvs"
version = "0.1.0"
authors = ["Komal Sai <bkomalsai@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"

[dependencies]
clap = { version = "4.4.6", features = ["derive", "env"] }
failure = "0.1.8"
serde = "1.0.188"
serde_json = "1.0.107"
